port: 8080
addr: "0.0.0.0"

# your domain
domain: "proxypool.leapcell.dev"

# database url
database_url: "postgresql://dcmvdwuatfwxiypibmru:gbzkmhmovxzyakchmwwkiwpblkdunl@9qasp5v56q8ckkf5dc.leapcellpool.com:6438/frmheehadazlfudskogj?sslmode=require"

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  - "source.yaml"
